name: laporkampus
description: Aplikasi Laporan Kerusakan Fasilitas Kampus
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management sederhana
  provider: ^6.1.2

  # HTTP request ke Laravel API
  http: ^1.2.1

  # Ambil foto dari kamera
  image_picker: ^1.1.2
  camera: ^0.11.0+2

  # Ambil lokasi GPS otomatis
  geolocator: ^12.0.0

  # Permintaan izin kamera & lokasi
  permission_handler: ^11.3.1

  # Simpan token login secara lokal & persisten (dipakai juga untuk dark mode)
  shared_preferences: ^2.2.3

  # Format tanggal
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true